### ISSUE TITLE
"before all" hook failure does not get propagated to teamcity build failure

### ISSUE THREAD

**Issue by mekdev** [travisjeffery/mocha-teamcity-reporter#35] opened 2018-01-07 21:41 UTC
This is on the latest 1.1.1
In this test suite we actually have 2 failures
1. a test failure
2. a before hook failure (which skips 3 tests) 

however only 1 test failure is reported
![screen shot 2018-01-07 at 1 39 21 pm](https://user-images.githubusercontent.com/2752830/34654443-6615edf4-f3b0-11e7-874b-51cb3d4934e3.png)

The only way to figure this out is to click in the build log and read mocha epilogue 

![screen shot 2018-01-07 at 1 39 34 pm](https://user-images.githubusercontent.com/2752830/34654435-50085ede-f3b0-11e7-8085-7ae03daa5cc1.png)

**Comment by jamie-sherriff** [comment] 2018-02-01 03:42
@mekdev Sorry for the delay, i have been trying to get ahold of @travisjeffery  to discuss how to publish new versions of the reporter but haven't got a reply. I am happy to work on this problem on my fork though.

**Comment by travisjeffery** [comment] 2018-02-01 04:45
@jamie-sherriff what's your email/username to add to npm?

**Comment by travisjeffery** [comment] 2018-02-01 04:52
@jamie-sherriff found your npm username and added you to the pkg.

**Comment by jamie-sherriff** [comment] 2018-02-01 08:00
@mekdev  i will merge over my changes and take a look at your issue after.

**Comment by jamie-sherriff** [comment] 2018-02-25 07:47
Had a look at this, will need to have a think about the best way to solve it is. Also looks like it was raised in #33

**Comment by mexisd** [comment] 2018-08-24 12:18
Hi @jamie-sherriff, is this fixed? I am on `2.4.0` and I still see the same behavior. When a before or after fails the name of the test is not logged in TeamCity.

**Comment by jamie-sherriff** [comment] 2018-08-26 10:47
Sorry @mexisd this never got merged in and is still on a branch as was waiting on the original poster for clarification on their expected behavior. Please give the branch a try as it subscribes to the hook event and won't rely on your implementation of a test name to match a specified name.

https://github.com/travisjeffery/mocha-teamcity-reporter/tree/fail-test-in-hook

If it solves your problem i can look at merging it in.

**Comment by mexisd** [comment] 2018-09-03 13:45
Hi @jamie-sherriff, thanks for your response. I will have a look at the branch, but do you know what I need to use that branch? At the moment it is very easy, as the only thing I needed to do was an npm install.

**Comment by mexisd** [comment] 2018-09-05 12:30
@jamie-sherriff I had a look. Overall seems to be working, but I have a reservation/question.

I tried with only one describe:
![image](https://user-images.githubusercontent.com/12252499/45093111-56948580-b10f-11e8-93ca-b39fc28a9a4f.png)

Then with a nested describe:
![image](https://user-images.githubusercontent.com/12252499/45093140-6d3adc80-b10f-11e8-94dd-1eea1dd22f69.png)

But if you go to the `Tests` tab in TeamCity, the `before`/`after` hooks will be displayed as Tests, which feels a bit strange. Especially, if this becomes the default and someone updates, the number of tests executed will be increased. Not sure if a user would expect that. Or perhaps we just document it and we accept it.

On the other hand I like it because it tells me why the test is slow, since now I can have metrics for the hooks as well. What are your thoughts?

![image](https://user-images.githubusercontent.com/12252499/45093289-df132600-b10f-11e8-9f58-79b815fc0b54.png)

**Comment by jamie-sherriff** [comment] 2018-09-11 06:17
@mexisd  Thanks for the feedback. I certainly agree with your comments around making it default behavior which is why i was thinking of keeping it optional until i do a major version bump.

If i merge the current behavior (and you turn it on with the option) in that would solve your problem  right?

**Comment by jamie-sherriff** [comment] 2018-09-18 08:12
This has been fixed and released under 2.5.0 with the reporter option recordHookFailures
Please let me know if there are any problems

**Closed by jamie-sherriff** 2018-09-18 08:12 UTC

**Comment by DJ-Glock** [comment] 2021-03-29 14:32
Hey @jamie-sherriff 
I faced the same problem and luckily found this issue before raising my own :)
But I have a concern. As I see by default reporter reports that hook was failed as a test:

`##teamcity[testFailed name='"before all" hook:`
But TeamCity ignores it at all, because there was no started message:
`##teamcity[testStarted name='"before all" hook:`

So did you try to raise this to TeamCity team?
Your solution with adding `testStarted` for each hook looks valid with a current TC implementation. But we starting to get a lot of hooks that look like tests.

Probably the best solution I can imagine is when TC can detect failed tests without `testStarted` tag. In this case it will show failed hooks as failed tests only when hooks fail. In other cases hooks will remain invisible like they should be, until `recordHookFailures` is set.

What do you think?
